### ISSUE TITLE
-osuset with space in the username wont allow it

### ISSUE THREAD

**Issue by GamebP** [darkchii/score-inspector#386]
To fix it. Make it so the commad can be allowed like `-osuset "<name>"`

![image](https://github.com/user-attachments/assets/8a0380fe-ebaf-4efe-a6f2-258945aa1c42)

**Comment by EngineerMark** [comment]
i have no control over the bots in the osualt channel (other than KirinoBot)
Sometimes the bot is a bit silly and refuses multiple time. Try a few times, otherwise report in #feature-ideas channel (is for bug reporting too basically)
