### ISSUE TITLE
Exclude lazer scores with relax

### ISSUE THREAD

**Issue by NoelleTGS** [darkchii/score-inspector#429]
Plays set with relax submit to leaderboards in lazer, so certain stats are inaccurate. This most likely affects autopilot as well.

The below play was set with relax.
![image](https://github.com/user-attachments/assets/a65db3b4-21d6-4cea-80cc-079e646a521c)

**Comment by EngineerMark** [comment]
This one's for the osu alternative discord, as I use their dataset. 
osu alt isnt fully moved to lazer yet, it strips off the "strange" mods as a temporary measure.
some day we will get correct data...
