### ISSUE TITLE
`TypeError: t[c] is undefined` when loading profiles

### ISSUE THREAD

**Issue by NoelleTGS** [darkchii/score-inspector#430]
Hopefully this one actually is on your end :p 

Profiles are occasionally failing to load with the site reporting "What went wrong: Unable to process scores". Can't determine a pattern since some seem to load fine but others will fail, and it's not consistent since the same profiles will load properly on other occasions (I've experienced this numerous times over the past few months).
[My profile](https://score.kirino.sh/user/18595366) for reference.

```
TypeError: t[c] is undefined
    i ScoresPeriodicProcessor.js:224
    o ScoresPeriodicProcessor.js:44
    $Sa ScoresPeriodicProcessor.js:31
    cba ScoresProcessor.js:130
    HNa User.js:111
    HNa User.js:28
    React 10
    u index.tsx:802
    push history.ts:664
    l hooks.tsx:244
    onClick AccountDropdown.js:29
    React 25
    H scheduler.production.min.js:13
    L scheduler.production.min.js:14
    7234 scheduler.production.min.js:14
    Webpack 12
User.js:113:28
    HNa User.js:113
    HNa User.js:28
    React 10
    u index.tsx:802
    push history.ts:664
    l hooks.tsx:244
    onClick AccountDropdown.js:29
    React 25
    H scheduler.production.min.js:13
    L scheduler.production.min.js:14
    (Async: EventHandlerNonNull)
    7234 scheduler.production.min.js:14
    Webpack 12
```

**Comment by EngineerMark** [comment]
I blame this on osudaily (its my fault)
Those lines are processing osudaily api data, but i do bad null-checks ;;
Planned on taking osudaily stuff out already to rely less on 3rd party apis, did it now for upcoming update
