### ISSUE TITLE
Length Completion maps on Users' profiles is wrong

### ISSUE THREAD

**Issue by ItzNico** [darkchii/score-inspector#431]
I've been completing long maps recently and for the 9-10 minutes and 10+ minute brackets the amount of maps displayed is wrong, 9-10 minutes should be 48 and 10+ minutes should be 198

Here's osu420's profile attached who has 100% on osu!alternative queries:
![image](https://github.com/user-attachments/assets/c99783cd-bb19-4614-9a66-7116cef21fb0)

**Comment by EngineerMark** [comment]
The website includes loved scores, since they are (pretty much) permanent leaderboards.
"!lc -u osu420 -loved true" gives the results above
