### ISSUE TITLE
Toggling "Hide completed packs" adds duplicate packs

### ISSUE THREAD

**Issue by redactdead** [darkchii/score-inspector#432]
On my profile, under the _Packs_ section, toggling the _Hide completed packs_ option on or off just adds duplicate packs to the end of the list.
![chrome_4juUcpJLJc](https://github.com/user-attachments/assets/7dea4cde-f2b3-4125-b8a3-dae59e0740bf)

**Comment by EngineerMark** [comment]
fixed in 7e73984662d5f8805864a553136c7e52f60f1b87
